from fastapi import APIRouter, HTTPException, BackgroundTasks, Header
from typing import Dict, Any

from app.schemas.notifications import LeaveApprovedEvent, PayrollPreviewEvent
from app.services.notification_service import hr_notification_service
from app.repos.notifications_repo import save_notification
from app.deps import verify_api_key

router = APIRouter(prefix="/events", tags=["events"])

@router.post("/leave-approved")
async def handle_leave_approved(
    event: LeaveApprovedEvent,
    background_tasks: BackgroundTasks,
    x_api_key: str = Header(..., alias="X-API-Key")
):
    """
    Handle LeaveApproved event - notify employee
    """
    verify_api_key(x_api_key)
    
    # Prepare notification for employee
    subject = "✅ Your Leave Request Has Been Approved"
    body = f"""
    Dear {event.employee_name},
    
    We're pleased to inform you that your leave request has been approved.
    
    📅 Leave Details:
    - Start Date: {event.start_date}
    - End Date: {event.end_date}
    - Approved By: {event.approved_by}
    - Approved At: {event.approved_at}
    - Request ID: {event.leave_request_id}
    
    Please ensure all pending tasks are completed before your leave begins.
    
    Best regards,
    HR Team - ARCA LTDA
    """
    
    # Send notification to employee
    result = await hr_notification_service.notify_employee(
        employee_email=event.employee_email,
        subject=subject,
        body=body,
        method="email"
    )
    
    # Save event and notification
    event_data = event.dict()
    event_data["notification_result"] = result
    event_data["event_type"] = "leave_approved"
    
    save_notification({
        **result,
        "event_type": "leave_approved",
        "event_data": event_data
    })
    
    return {
        "event": "leave_approved",
        "employee_notified": event.employee_email,
        "notification_status": result.get("status", "unknown"),
        "notification_id": result.get("id")
    }

@router.post("/payroll-preview-ready")
async def handle_payroll_preview_ready(
    event: PayrollPreviewEvent,
    background_tasks: BackgroundTasks,
    x_api_key: str = Header(..., alias="X-API-Key")
):
    """
    Handle PayrollPreviewReady event - notify HR team
    """
    verify_api_key(x_api_key)
    
    # Prepare notification for HR team
    subject = f"📊 Payroll Preview Ready - {event.payroll_period}"
    body = f"""
    Payroll Preview Notification
    
    The payroll preview for {event.payroll_period} is now ready for review.
    
    📋 Preview Details:
    - Period: {event.payroll_period}
    - Total Employees: {event.total_employees}
    - Generated By: {event.generated_by}
    - Generated At: {event.generated_at}
    - Preview ID: {event.preview_id}
    {f"- Preview URL: {event.preview_url}" if event.preview_url else ""}
    
    Please review the payroll preview and approve or make adjustments as needed.
    
    Generated by: {event.generated_by}
    """
    
    # Send notifications to all HR emails
    results = await hr_notification_service.notify_hr_team(
        subject=subject,
        body=body,
        method="email"
    )
    
    # Save event and notifications
    event_data = event.dict()
    event_data["notifications_sent"] = len(results)
    
    save_notification({
        "event_type": "payroll_preview_ready",
        "event_data": event_data,
        "hr_notifications": results,
        "status": "processed",
        "sent_at": event.generated_at
    })
    
    return {
        "event": "payroll_preview_ready",
        "hr_team_notified": len(results),
        "notifications_sent": results
    }

@router.post("/test-event")
async def test_event_handler(
    event_type: str = "leave_approved",
    x_api_key: str = Header(..., alias="X-API-Key")
):
    """
    Test endpoint for event handlers
    """
    verify_api_key(x_api_key)
    
    if event_type == "leave_approved":
        test_event = LeaveApprovedEvent(
            employee_email="test.employee@arca.ltd",
            employee_name="Test Employee",
            leave_request_id="TEST-001",
            start_date="2024-01-15",
            end_date="2024-01-20",
            approved_by="Test Manager",
            approved_at="2024-01-10T10:00:00Z"
        )
        return await handle_leave_approved(test_event, BackgroundTasks(), x_api_key)
    
    elif event_type == "payroll_preview_ready":
        test_event = PayrollPreviewEvent(
            payroll_period="January 2024",
            preview_id="PREVIEW-001",
            generated_by="Payroll System",
            generated_at="2024-01-05T15:30:00Z",
            total_employees=150,
            preview_url="https://arca.ltd/payroll/preview/PREVIEW-001"
        )
        return await handle_payroll_preview_ready(test_event, BackgroundTasks(), x_api_key)
    
    else:
        raise HTTPException(status_code=400, detail="Invalid event type")